### ISSUE TITLE
Register.py 报错

### ISSUE THREAD

**Issue by harrytsz** [BeiXi1949/Face-Recognition_FaceNet_PyTorch#3]
@BeiXi1949  您好，我在Ubuntu18+ Python3.7（Anaconda） + Pytorch1.0 的环境下运行 Register.py 文件的时候出现了以下的报错信息，不知道哪里出现了问题？

`12
Person: h2
/===No csv...Creating...
/===Ceated!
/------Finished Recording------/
/===No csv...Creating...
/===Ceated!
Captured image : h21
Captured image : h22
Captured image : h23
Captured image : h24
Captured image : h25
Captured image : h26
Captured image : h27
Captured image : h28
Captured image : h29
Captured image : h210
Captured image : h211
Captured image : h212
Captured image : h213
Captured image : h214
Captured image : h215
Captured image : h216
Captured image : h217
Captured image : h218
Captured image : h219
Captured image : h220
Captured image : h221
Captured image : h222
Captured image : h223
Captured image : h224
Captured image : h225
Captured image : h226
Captured image : h227
Captured image : h228
Captured image : h229
Captured image : h230
Captured image : h231
Captured image : h232
Captured image : h233
Captured image : h234
Captured image : h235
Captured image : h236
Captured image : h237
Captured image : h238
Captured image : h239
Captured image : h240
Captured image : h241
Captured image : h242
Captured image : h243
Captured image : h244
Captured image : h245
Captured image : h246
Captured image : h247
Captured image : h248
Captured image : h249
Captured image : h250
Captured image : h251
Captured image : h252
Captured image : h253
Captured image : h254
Captured image : h255
Captured image : h256
Captured image : h257
Captured image : h258
Captured image : h259
Captured image : h260
Captured image : h261
Captured image : h262
Captured image : h263
Captured image : h264
Captured image : h265
Captured image : h266
Captured image : h267
Captured image : h268
Captured image : h269
Captured image : h270
Captured image : h271
Captured image : h272
Captured image : h273
Captured image : h274
Captured image : h275
Captured image : h276
Captured image : h277
Captured image : h278
Captured image : h279
Captured image : h280
Captured image : h281
Captured image : h282
Captured image : h283
Captured image : h284
Captured image : h285
Captured image : h286
Captured image : h287
Captured image : h288
Captured image : h289
Captured image : h290
Captured image : h291
Captured image : h292
Captured image : h293
Captured image : h294
Captured image : h295
Captured image : h296
Captured image : h297
Captured image : h298
Captured image : h299
Captured image : h2100
Captured image : h2100
Captured image : h2100
Captured image : h2100
Captured image : h2100
Captured image : h2100
Captured image : h2100
Captured image : h2100
Captured image : h2100
Captured image : h2100
Captured image : h2101
Captured image : h2101
Captured image : h2102
Captured image : h2103
Captured image : h2104
Captured image : h2105
Captured image : h2106
Captured image : h2107
Captured image : h2108
Captured image : h2109
Captured image : h2110
Captured image : h2111
Captured image : h2112
Captured image : h2113
Captured image : h2114
Captured image : h2115
Captured image : h2116
Captured image : h2117
Captured image : h2118
Captured image : h2119
Captured image : h2120
Captured image : h2121
Captured image : h2122
Captured image : h2123
Captured image : h2124
Captured image : h2125
Captured image : h2126
Captured image : h2127
Captured image : h2128
Captured image : h2129
Captured image : h2130
Captured image : h2131
Captured image : h2132
Captured image : h2133
Captured image : h2134
Captured image : h2135
Captured image : h2136
Captured image : h2137
Captured image : h2138
Captured image : h2139
Captured image : h2140
Captured image : h2141
Captured image : h2142
Captured image : h2143
Captured image : h2144
Captured image : h2145
Captured image : h2146
Captured image : h2147
Captured image : h2148
Captured image : h2149
Captured image : h2150
/------Finished Reigister------/

/------Start Processing Vectors------/
Write Vector success!h2at03-7月-2019_12:25:41
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
Find error img! Delete
Error path drop
/----Finished----/
check loading unknown data
Unknown aligned and csv is prepared
checking unknown vectors
/----Finished----/
Process Process-13:
Traceback (most recent call last):
  File "/home/harrytsz/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/harrytsz/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/harrytsz/Documents/DeepLearning/Face-Recognition_FaceNet_PyTorch-master/Register.py", line 238, in train_knn
    training_KNN(path)
  File "/home/harrytsz/Documents/DeepLearning/Face-Recognition_FaceNet_PyTorch-master/KNN_builder.py", line 74, in training_KNN
    X_train,Y_train=generate_dataset(csv_path)
  File "/home/harrytsz/Documents/DeepLearning/Face-Recognition_FaceNet_PyTorch-master/KNN_builder.py", line 56, in generate_dataset
    data = falttern(read_path)
  File "/home/harrytsz/Documents/DeepLearning/Face-Recognition_FaceNet_PyTorch-master/KNN_builder.py", line 30, in falttern
    vector=np.load(path)
  File "/home/harrytsz/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] 没有那个文件或目录: 'Null'

Process finished with exit code 0`

**Comment by bensentray** [comment]
你好，我的环境是pytorch 1.1, python 3.7运行registor.py时报错：
    from .SpatialCrossMapLRN_temp import SpatialCrossMapLRN_temp
  File "/Users/macx/Documents/src/face_recog/Face-Recognition_FaceNet_PyTorch/utils/SpatialCrossMapLRN_temp.py", line 8, in <module>
    from torch.legacy.nn.Module import Module
ModuleNotFoundError: No module named 'torch.legacy'
请问这个from torch.legacy.nn.Module import Module 是不是pytorch1.1版本的torch.nn.Module呢？

**Comment by bensentray** [comment]
File "/Users/macx/Documents/src/face_recog/Face-Recognition_FaceNet_PyTorch/utils/openface_pytorch.py", line 18, in <module>
    from .SpatialCrossMapLRN_temp import SpatialCrossMapLRN_temp
  File "/Users/macx/Documents/src/face_recog/Face-Recognition_FaceNet_PyTorch/utils/SpatialCrossMapLRN_temp.py", line 10, in <module>
    from torch.legacy.nn.utils import clear
ModuleNotFoundError: No module named 'torch.legacy'
这个clear是什么函数呢

**Comment by bensentray** [comment]
我也跑到了您报错的这个步骤，不知为啥

**Comment by bensentray** [comment]
发现执行outputs = facenet(img_tensor.unsqueeze(0))这句的时候报错：NotImplementedError

**Comment by chandler1142** [comment]
This issue seems caused by the implementation of SpatialCrossMapLRN_temp. You can try to redefine the module layers in openface_pytorch.py and skip layer5 and layer12, which mainly to enhance the recognize rate. It will not quite impact the eventually result a lot if you skip these two layers. Hope this would be help.

**Comment by FangLinLin338** [comment]
在运行Register.py的时候出现错误，在第337行的temp_path=i[2]，报错是IndexError: list index out of range，请问该怎么解决呢？

**Comment by SaltyBlueBerry** [comment]
temp_path=i[2]，报错是IndexError: list index out of range楼上这个错误我也遇到了，并且在运行recoginizer.py时出现Process finished with exit code -1073741819 (0xC0000005)，请问有人知道如何解决吗？
